###############################################################################
# Created by write_sdc
###############################################################################
current_design chip_core
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 45.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {analog}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_in[0]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_in[1]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_in[2]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_in[3]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_in[0]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_in[1]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_in[2]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_in[3]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_in[4]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_in[5]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_in[6]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_in[7]}]
set_input_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {analog}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_cs[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_ie[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_oe[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_out[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pd[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_pu[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bidir_sl[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pd[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pd[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pd[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pd[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pd[4]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pd[5]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pd[6]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pd[7]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pu[0]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pu[1]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pu[2]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pu[3]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pu[4]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pu[5]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pu[6]}]
set_output_delay 8.0000 -clock [get_clocks {clk}] -add_delay [get_ports {input_pu[7]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0729 [get_ports {analog}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_cs[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_ie[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_oe[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_out[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_pd[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_pu[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_sl[0]}]
set_load -pin_load 0.0729 [get_ports {input_pd[7]}]
set_load -pin_load 0.0729 [get_ports {input_pd[6]}]
set_load -pin_load 0.0729 [get_ports {input_pd[5]}]
set_load -pin_load 0.0729 [get_ports {input_pd[4]}]
set_load -pin_load 0.0729 [get_ports {input_pd[3]}]
set_load -pin_load 0.0729 [get_ports {input_pd[2]}]
set_load -pin_load 0.0729 [get_ports {input_pd[1]}]
set_load -pin_load 0.0729 [get_ports {input_pd[0]}]
set_load -pin_load 0.0729 [get_ports {input_pu[7]}]
set_load -pin_load 0.0729 [get_ports {input_pu[6]}]
set_load -pin_load 0.0729 [get_ports {input_pu[5]}]
set_load -pin_load 0.0729 [get_ports {input_pu[4]}]
set_load -pin_load 0.0729 [get_ports {input_pu[3]}]
set_load -pin_load 0.0729 [get_ports {input_pu[2]}]
set_load -pin_load 0.0729 [get_ports {input_pu[1]}]
set_load -pin_load 0.0729 [get_ports {input_pu[0]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_4 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bidir_in[3]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bidir_in[2]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bidir_in[1]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bidir_in[0]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_in[7]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_in[6]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_in[5]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_in[4]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_in[3]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_in[2]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_in[1]}]
set_driving_cell -lib_cell gf180mcu_fd_sc_mcu7t5v0__inv_1 -pin {ZN} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {input_in[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 3.0000 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
